-- Slice 3 Gate C — atomic migration + verification pack
-- Expected preflight recorded 29 Aug 2026: generated_outputs=7,
-- native_social_post_artifacts=2, native_offer_artifacts=3,
-- native_whatsapp_draft_artifacts absent (404).
-- Safe to run only for the bounded UUID-Nik canary authorization.

begin;

do $$
begin
  if (select count(*) from public.generated_outputs) <> 7 then
    raise exception 'Gate C blocked: generated_outputs baseline drift';
  end if;
  if (select count(*) from public.native_social_post_artifacts) <> 2 then
    raise exception 'Gate C blocked: native_social_post_artifacts baseline drift';
  end if;
  if (select count(*) from public.native_offer_artifacts) <> 3 then
    raise exception 'Gate C blocked: native_offer_artifacts baseline drift';
  end if;
end
$$;

-- Slice 3 controlled in-place canary: additive shadow table only.
-- SAFE BOUNDARY: this migration MUST NOT alter public.generated_outputs,
-- public.native_social_post_artifacts, public.native_offer_artifacts or any 1.0 policy/data.


create table if not exists public.native_whatsapp_draft_artifacts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_id uuid not null,
  request jsonb not null check (jsonb_typeof(request) = 'object'),
  artifact jsonb not null check (jsonb_typeof(artifact) = 'object'),
  generation jsonb not null check (jsonb_typeof(generation) = 'object'),
  rendered_text text not null check (octet_length(rendered_text) <= 50000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint native_whatsapp_user_request_unique unique (user_id, request_id)
);

alter table public.native_whatsapp_draft_artifacts enable row level security;
alter table public.native_whatsapp_draft_artifacts force row level security;

-- Idempotent policy install, scoped only to the new Slice 3 table.
drop policy if exists "native whatsapp drafts owner select" on public.native_whatsapp_draft_artifacts;

revoke all on table public.native_whatsapp_draft_artifacts from anon;
revoke all on table public.native_whatsapp_draft_artifacts from authenticated;
grant select on table public.native_whatsapp_draft_artifacts to authenticated;

create policy "native whatsapp drafts owner select"
on public.native_whatsapp_draft_artifacts
for select
to authenticated
using ((select auth.uid()) = user_id);

-- Mutations are route-only through service role after verified auth, entitlement,
-- UUID allowlist, origin check, validation, quota, and explicit owner predicates.
create index if not exists native_whatsapp_user_created_idx
  on public.native_whatsapp_draft_artifacts (user_id, created_at desc);

-- Read-only verification for Slice 3 native WhatsApp draft shadow table.
-- Run after the additive migration. Raises on any failed invariant.

do $$
declare
  rls_enabled boolean;
  rls_forced boolean;
  owner_policy_count integer;
  forbidden_mutation_grants integer;
  unique_count integer;
begin
  select c.relrowsecurity, c.relforcerowsecurity
    into rls_enabled, rls_forced
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relname = 'native_whatsapp_draft_artifacts';

  if coalesce(rls_enabled, false) is not true then
    raise exception 'native_whatsapp_draft_artifacts RLS is not enabled';
  end if;
  if coalesce(rls_forced, false) is not true then
    raise exception 'native_whatsapp_draft_artifacts FORCE RLS is not enabled';
  end if;

  select count(*) into owner_policy_count
  from pg_policies
  where schemaname = 'public'
    and tablename = 'native_whatsapp_draft_artifacts'
    and policyname = 'native whatsapp drafts owner select'
    and cmd = 'SELECT'
    and 'authenticated' = any(roles);

  if owner_policy_count <> 1 then
    raise exception 'owner SELECT policy missing or duplicated';
  end if;

  select count(*) into forbidden_mutation_grants
  from information_schema.role_table_grants
  where table_schema = 'public'
    and table_name = 'native_whatsapp_draft_artifacts'
    and grantee in ('anon', 'authenticated')
    and privilege_type in ('INSERT', 'UPDATE', 'DELETE', 'TRUNCATE', 'TRIGGER', 'REFERENCES');

  if forbidden_mutation_grants <> 0 then
    raise exception 'direct client mutation grants detected';
  end if;

  select count(*) into unique_count
  from pg_constraint con
  join pg_class c on c.oid = con.conrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'native_whatsapp_draft_artifacts'
    and con.conname = 'native_whatsapp_user_request_unique'
    and con.contype = 'u';

  if unique_count <> 1 then
    raise exception 'durable user/request unique constraint missing';
  end if;

  if not exists (
    select 1 from pg_indexes
    where schemaname = 'public'
      and tablename = 'native_whatsapp_draft_artifacts'
      and indexname = 'native_whatsapp_user_created_idx'
  ) then
    raise exception 'owner/time index missing';
  end if;
end
$$;

do $$
begin
  if (select count(*) from public.generated_outputs) <> 7
     or (select count(*) from public.native_social_post_artifacts) <> 2
     or (select count(*) from public.native_offer_artifacts) <> 3
     or (select count(*) from public.native_whatsapp_draft_artifacts) <> 0 then
    raise exception 'Gate C blocked: post-DDL count invariant failed';
  end if;
end
$$;

commit;

select
  'SLICE3_GATE_C_PASS' as result,
  (select count(*) from public.generated_outputs) as generated_outputs,
  (select count(*) from public.native_social_post_artifacts) as native_social_post_artifacts,
  (select count(*) from public.native_offer_artifacts) as native_offer_artifacts,
  (select count(*) from public.native_whatsapp_draft_artifacts) as native_whatsapp_draft_artifacts;
