-- AI4Bisnes Slice 1 — Gate 2 atomic apply + verify
-- Bounded scope: additive native_social_post_artifacts only.
-- Safe to re-run. STOP on any exception.

create temporary table _legacy_generated_outputs_policies_before on commit preserve rows as
select policyname, cmd, roles::text, coalesce(qual,''), coalesce(with_check,'')
from pg_policies
where schemaname='public' and tablename='generated_outputs';

create temporary table _legacy_generated_outputs_count_before on commit preserve rows as
select count(*)::bigint as row_count from public.generated_outputs;

1|-- Slice 1 controlled in-place canary: additive shadow table only.
2|-- SAFE BOUNDARY: this migration MUST NOT alter public.generated_outputs or any 1.0 policy/data.
3|begin;
4|
5|create table if not exists public.native_social_post_artifacts (
6|  id bigint generated by default as identity primary key,
7|  user_id uuid not null references auth.users(id) on delete cascade,
8|  request_id uuid not null,
9|  request jsonb not null check (jsonb_typeof(request) = 'object'),
10|  artifact jsonb not null check (jsonb_typeof(artifact) = 'object'),
11|  generation jsonb not null check (jsonb_typeof(generation) = 'object'),
12|  rendered_text text not null check (octet_length(rendered_text) <= 50000),
13|  created_at timestamptz not null default now(),
14|  updated_at timestamptz not null default now(),
15|  constraint native_social_post_user_request_unique unique (user_id, request_id)
16|);
17|
18|alter table public.native_social_post_artifacts enable row level security;
19|alter table public.native_social_post_artifacts force row level security;
20|
21|-- Idempotent policy install, scoped only to the new Slice 1 table.
22|drop policy if exists "native social posts owner select" on public.native_social_post_artifacts;
23|
24|revoke all on table public.native_social_post_artifacts from anon;
25|revoke all on table public.native_social_post_artifacts from authenticated;
26|grant select on table public.native_social_post_artifacts to authenticated;
27|
28|create policy "native social posts owner select"
29|on public.native_social_post_artifacts
30|for select
31|to authenticated
32|using ((select auth.uid()) = user_id);
33|
34|-- Mutations are route-only through service role after verified auth, entitlement,
35|-- UUID allowlist, origin check, validation, quota, and explicit owner predicates.
36|create index if not exists native_social_post_user_created_idx
37|  on public.native_social_post_artifacts (user_id, created_at desc);
38|
39|commit;
40|

1|-- Verify controlled in-place canary shadow table on the main Supabase project.
2|-- This does not mutate data. Run after 202608260001_native_social_post_rls.sql.
3|do $$
4|declare
5|  rls_enabled boolean;
6|  rls_forced boolean;
7|  owner_policy_count integer;
8|  mutation_grant_count integer;
9|  index_count integer;
10|  unique_count integer;
11|begin
12|  select c.relrowsecurity, c.relforcerowsecurity
13|    into rls_enabled, rls_forced
14|  from pg_class c
15|  join pg_namespace n on n.oid = c.relnamespace
16|  where n.nspname = 'public' and c.relname = 'native_social_post_artifacts';
17|
18|  if coalesce(rls_enabled, false) is not true then
19|    raise exception 'native_social_post_artifacts RLS is not enabled';
20|  end if;
21|  if coalesce(rls_forced, false) is not true then
22|    raise exception 'native_social_post_artifacts FORCE RLS is not enabled';
23|  end if;
24|
25|  select count(*) into owner_policy_count
26|  from pg_policies
27|  where schemaname = 'public'
28|    and tablename = 'native_social_post_artifacts'
29|    and policyname = 'native social posts owner select'
30|    and cmd = 'SELECT'
31|    and roles = array['authenticated']::name[]
32|    and qual like '%auth.uid()%user_id%';
33|  if owner_policy_count <> 1 then
34|    raise exception 'owner SELECT policy is missing or malformed';
35|  end if;
36|
37|  select count(*) into mutation_grant_count
38|  from information_schema.role_table_grants
39|  where table_schema = 'public'
40|    and table_name = 'native_social_post_artifacts'
41|    and grantee in ('anon', 'authenticated')
42|    and privilege_type in ('INSERT', 'UPDATE', 'DELETE', 'TRUNCATE');
43|  if mutation_grant_count <> 0 then
44|    raise exception 'direct client mutation grants remain on native_social_post_artifacts';
45|  end if;
46|
47|  select count(*) into index_count
48|  from pg_indexes
49|  where schemaname = 'public'
50|    and tablename = 'native_social_post_artifacts'
51|    and indexname = 'native_social_post_user_created_idx';
52|  if index_count <> 1 then
53|    raise exception 'Slice 1 owner/time index missing';
54|  end if;
55|
56|  select count(*) into unique_count
57|  from pg_constraint
58|  where conrelid = 'public.native_social_post_artifacts'::regclass
59|    and conname = 'native_social_post_user_request_unique'
60|    and contype = 'u';
61|  if unique_count <> 1 then
62|    raise exception 'durable request idempotency constraint missing';
63|  end if;
64|end
65|$$;
66|
67|-- Runtime canary gate must additionally run direct PostgREST checks:
68|-- anon denied; allowlisted owner can SELECT own row; non-owner receives no row;
69|-- authenticated direct INSERT/UPDATE/DELETE denied; generated_outputs 1.0 smoke test unchanged.
70|

-- Legacy invariants: count and policy definitions must be identical.
do $$
declare
  before_count bigint;
  after_count bigint;
begin
  select row_count into before_count from _legacy_generated_outputs_count_before;
  select count(*)::bigint into after_count from public.generated_outputs;
  if before_count <> after_count then
    raise exception 'LEGACY DRIFT: generated_outputs count changed from % to %', before_count, after_count;
  end if;

  if exists (
    (select policyname,cmd,roles,qual,with_check from _legacy_generated_outputs_policies_before
     except
     select policyname,cmd,roles::text,coalesce(qual,''),coalesce(with_check,'')
     from pg_policies where schemaname='public' and tablename='generated_outputs')
    union all
    (select policyname,cmd,roles::text,coalesce(qual,''),coalesce(with_check,'')
     from pg_policies where schemaname='public' and tablename='generated_outputs'
     except
     select policyname,cmd,roles,qual,with_check from _legacy_generated_outputs_policies_before)
  ) then
    raise exception 'LEGACY DRIFT: generated_outputs policies changed';
  end if;
end
$$;

select 'SLICE1_GATE2_PASS' as result,
       (select count(*) from public.generated_outputs) as generated_outputs_unchanged_count,
       (select count(*) from public.native_social_post_artifacts) as shadow_artifact_count;
