-- AI4Bisnes Slice 2 — Gate 2 atomic apply + verify (native_offer_artifacts)
-- Bounded scope: additive native_offer_artifacts sahaja.
-- Safe to re-run. STOP on any exception.

create temporary table _s2_legacy_go_policies_before on commit preserve rows as
select policyname, cmd, roles::text as roles, coalesce(qual,'') as qual, coalesce(with_check,'') as with_check
from pg_policies
where schemaname='public' and tablename='generated_outputs';

create temporary table _s2_legacy_go_count_before on commit preserve rows as
select count(*)::bigint as row_count from public.generated_outputs;

create temporary table _s2_legacy_s1_policies_before on commit preserve rows as
select policyname, cmd, roles::text as roles, coalesce(qual,'') as qual, coalesce(with_check,'') as with_check
from pg_policies
where schemaname='public' and tablename='native_social_post_artifacts';

create temporary table _s2_legacy_s1_count_before on commit preserve rows as
select count(*)::bigint as row_count from public.native_social_post_artifacts;

-- Slice 2 controlled in-place canary: additive shadow table only.
-- SAFE BOUNDARY: this migration MUST NOT alter public.generated_outputs,
-- public.native_social_post_artifacts or any 1.0 policy/data.
begin;

create table if not exists public.native_offer_artifacts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_id uuid not null,
  request jsonb not null check (jsonb_typeof(request) = 'object'),
  artifact jsonb not null check (jsonb_typeof(artifact) = 'object'),
  generation jsonb not null check (jsonb_typeof(generation) = 'object'),
  rendered_text text not null check (octet_length(rendered_text) <= 50000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint native_offer_user_request_unique unique (user_id, request_id)
);

alter table public.native_offer_artifacts enable row level security;
alter table public.native_offer_artifacts force row level security;

-- Idempotent policy install, scoped only to the new Slice 2 table.
drop policy if exists "native offers owner select" on public.native_offer_artifacts;

revoke all on table public.native_offer_artifacts from anon;
revoke all on table public.native_offer_artifacts from authenticated;
grant select on table public.native_offer_artifacts to authenticated;

create policy "native offers owner select"
on public.native_offer_artifacts
for select
to authenticated
using ((select auth.uid()) = user_id);

-- Mutations are route-only through service role after verified auth, entitlement,
-- UUID allowlist, origin check, validation, quota, and explicit owner predicates.
create index if not exists native_offer_user_created_idx
  on public.native_offer_artifacts (user_id, created_at desc);

commit;

-- Verify controlled in-place canary shadow table for Slice 2 (native_offer_artifacts).
-- Read-only. Run after 202608280001_native_offer_rls.sql.
do $$
declare
  rls_enabled boolean;
  rls_forced boolean;
  owner_policy_count integer;
  mutation_grant_count integer;
  index_count integer;
  unique_count integer;
begin
  select c.relrowsecurity, c.relforcerowsecurity
    into rls_enabled, rls_forced
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relname = 'native_offer_artifacts';

  if coalesce(rls_enabled, false) is not true then
    raise exception 'native_offer_artifacts RLS is not enabled';
  end if;
  if coalesce(rls_forced, false) is not true then
    raise exception 'native_offer_artifacts FORCE RLS is not enabled';
  end if;

  select count(*) into owner_policy_count
  from pg_policies
  where schemaname = 'public'
    and tablename = 'native_offer_artifacts'
    and policyname = 'native offers owner select'
    and cmd = 'SELECT'
    and roles = array['authenticated']::name[]
    and qual like '%auth.uid()%user_id%';
  if owner_policy_count <> 1 then
    raise exception 'owner SELECT policy is missing or malformed';
  end if;

  select count(*) into mutation_grant_count
  from information_schema.role_table_grants
  where table_schema = 'public'
    and table_name = 'native_offer_artifacts'
    and grantee in ('anon', 'authenticated')
    and privilege_type in ('INSERT', 'UPDATE', 'DELETE', 'TRUNCATE');
  if mutation_grant_count <> 0 then
    raise exception 'direct client mutation grants remain on native_offer_artifacts';
  end if;

  select count(*) into index_count
  from pg_indexes
  where schemaname = 'public'
    and tablename = 'native_offer_artifacts'
    and indexname = 'native_offer_user_created_idx';
  if index_count <> 1 then
    raise exception 'Slice 2 owner/time index missing';
  end if;

  select count(*) into unique_count
  from pg_constraint
  where conrelid = 'public.native_offer_artifacts'::regclass
    and conname = 'native_offer_user_request_unique'
    and contype = 'u';
  if unique_count <> 1 then
    raise exception 'durable request idempotency constraint missing';
  end if;
end
$$;


-- Legacy drift guards: counts and policies must be identical.
do $$
declare
  go_before bigint; go_after bigint;
  s1_before bigint; s1_after bigint;
begin
  select row_count into go_before from _s2_legacy_go_count_before;
  select count(*)::bigint into go_after from public.generated_outputs;
  if go_before <> go_after then
    raise exception 'LEGACY DRIFT: generated_outputs count changed from % to %', go_before, go_after;
  end if;

  select row_count into s1_before from _s2_legacy_s1_count_before;
  select count(*)::bigint into s1_after from public.native_social_post_artifacts;
  if s1_before <> s1_after then
    raise exception 'LEGACY DRIFT: native_social_post_artifacts count changed from % to %', s1_before, s1_after;
  end if;

  if exists (
    (select policyname,cmd,roles,qual,with_check from _s2_legacy_go_policies_before
     except select policyname,cmd,roles::text,coalesce(qual,'') as qual,coalesce(with_check,'') as with_check
     from pg_policies where schemaname='public' and tablename='generated_outputs')
    union all
    (select policyname,cmd,roles::text,coalesce(qual,'') as qual,coalesce(with_check,'') as with_check
     from pg_policies where schemaname='public' and tablename='generated_outputs'
     except select policyname,cmd,roles,qual,with_check from _s2_legacy_go_policies_before)
    union all
    (select policyname,cmd,roles,qual,with_check from _s2_legacy_s1_policies_before
     except select policyname,cmd,roles::text,coalesce(qual,'') as qual,coalesce(with_check,'') as with_check
     from pg_policies where schemaname='public' and tablename='native_social_post_artifacts')
    union all
    (select policyname,cmd,roles::text,coalesce(qual,'') as qual,coalesce(with_check,'') as with_check
     from pg_policies where schemaname='public' and tablename='native_social_post_artifacts'
     except select policyname,cmd,roles,qual,with_check from _s2_legacy_s1_policies_before)
  ) then
    raise exception 'LEGACY DRIFT: generated_outputs/native_social_post_artifacts policies changed';
  end if;
end
$$;

select 'SLICE2_GATE2_PASS' as result,
       (select count(*) from public.generated_outputs) as generated_outputs_unchanged,
       (select count(*) from public.native_social_post_artifacts) as slice1_unchanged,
       (select count(*) from public.native_offer_artifacts) as slice2_rows;
