-- AI4Bisnes Slice 1 — Gate 2 atomic apply + verify
-- Bounded scope: additive native_social_post_artifacts only.
-- Safe to re-run. STOP on any exception.

create temporary table _legacy_generated_outputs_policies_before on commit preserve rows as
select policyname, cmd, roles::text, coalesce(qual,'') as qual, coalesce(with_check,'') as with_check
from pg_policies
where schemaname='public' and tablename='generated_outputs';

create temporary table _legacy_generated_outputs_count_before on commit preserve rows as
select count(*)::bigint as row_count from public.generated_outputs;

-- Slice 1 controlled in-place canary: additive shadow table only.
-- SAFE BOUNDARY: this migration MUST NOT alter public.generated_outputs or any 1.0 policy/data.
begin;

create table if not exists public.native_social_post_artifacts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_id uuid not null,
  request jsonb not null check (jsonb_typeof(request) = 'object'),
  artifact jsonb not null check (jsonb_typeof(artifact) = 'object'),
  generation jsonb not null check (jsonb_typeof(generation) = 'object'),
  rendered_text text not null check (octet_length(rendered_text) <= 50000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint native_social_post_user_request_unique unique (user_id, request_id)
);

alter table public.native_social_post_artifacts enable row level security;
alter table public.native_social_post_artifacts force row level security;

-- Idempotent policy install, scoped only to the new Slice 1 table.
drop policy if exists "native social posts owner select" on public.native_social_post_artifacts;

revoke all on table public.native_social_post_artifacts from anon;
revoke all on table public.native_social_post_artifacts from authenticated;
grant select on table public.native_social_post_artifacts to authenticated;

create policy "native social posts owner select"
on public.native_social_post_artifacts
for select
to authenticated
using ((select auth.uid()) = user_id);

-- Mutations are route-only through service role after verified auth, entitlement,
-- UUID allowlist, origin check, validation, quota, and explicit owner predicates.
create index if not exists native_social_post_user_created_idx
  on public.native_social_post_artifacts (user_id, created_at desc);

commit;

-- Verify controlled in-place canary shadow table on the main Supabase project.
-- This does not mutate data. Run after 202608260001_native_social_post_rls.sql.
do $$
declare
  rls_enabled boolean;
  rls_forced boolean;
  owner_policy_count integer;
  mutation_grant_count integer;
  index_count integer;
  unique_count integer;
begin
  select c.relrowsecurity, c.relforcerowsecurity
    into rls_enabled, rls_forced
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relname = 'native_social_post_artifacts';

  if coalesce(rls_enabled, false) is not true then
    raise exception 'native_social_post_artifacts RLS is not enabled';
  end if;
  if coalesce(rls_forced, false) is not true then
    raise exception 'native_social_post_artifacts FORCE RLS is not enabled';
  end if;

  select count(*) into owner_policy_count
  from pg_policies
  where schemaname = 'public'
    and tablename = 'native_social_post_artifacts'
    and policyname = 'native social posts owner select'
    and cmd = 'SELECT'
    and roles = array['authenticated']::name[]
    and qual like '%auth.uid()%user_id%';
  if owner_policy_count <> 1 then
    raise exception 'owner SELECT policy is missing or malformed';
  end if;

  select count(*) into mutation_grant_count
  from information_schema.role_table_grants
  where table_schema = 'public'
    and table_name = 'native_social_post_artifacts'
    and grantee in ('anon', 'authenticated')
    and privilege_type in ('INSERT', 'UPDATE', 'DELETE', 'TRUNCATE');
  if mutation_grant_count <> 0 then
    raise exception 'direct client mutation grants remain on native_social_post_artifacts';
  end if;

  select count(*) into index_count
  from pg_indexes
  where schemaname = 'public'
    and tablename = 'native_social_post_artifacts'
    and indexname = 'native_social_post_user_created_idx';
  if index_count <> 1 then
    raise exception 'Slice 1 owner/time index missing';
  end if;

  select count(*) into unique_count
  from pg_constraint
  where conrelid = 'public.native_social_post_artifacts'::regclass
    and conname = 'native_social_post_user_request_unique'
    and contype = 'u';
  if unique_count <> 1 then
    raise exception 'durable request idempotency constraint missing';
  end if;
end
$$;

-- Runtime canary gate must additionally run direct PostgREST checks:
-- anon denied; allowlisted owner can SELECT own row; non-owner receives no row;
-- authenticated direct INSERT/UPDATE/DELETE denied; generated_outputs 1.0 smoke test unchanged.


-- Legacy invariants: count and policy definitions must be identical.
do $$
declare
  before_count bigint;
  after_count bigint;
begin
  select row_count into before_count from _legacy_generated_outputs_count_before;
  select count(*)::bigint into after_count from public.generated_outputs;
  if before_count <> after_count then
    raise exception 'LEGACY DRIFT: generated_outputs count changed from % to %', before_count, after_count;
  end if;

  if exists (
    (select policyname,cmd,roles,qual,with_check from _legacy_generated_outputs_policies_before
     except
     select policyname,cmd,roles::text,coalesce(qual,'') as qual,coalesce(with_check,'') as with_check
     from pg_policies where schemaname='public' and tablename='generated_outputs')
    union all
    (select policyname,cmd,roles::text,coalesce(qual,'') as qual,coalesce(with_check,'') as with_check
     from pg_policies where schemaname='public' and tablename='generated_outputs'
     except
     select policyname,cmd,roles,qual,with_check from _legacy_generated_outputs_policies_before)
  ) then
    raise exception 'LEGACY DRIFT: generated_outputs policies changed';
  end if;
end
$$;

select 'SLICE1_GATE2_PASS' as result,
       (select count(*) from public.generated_outputs) as generated_outputs_unchanged_count,
       (select count(*) from public.native_social_post_artifacts) as shadow_artifact_count;
