-- Slice 2 controlled in-place canary: additive shadow table only.
-- SAFE BOUNDARY: this migration MUST NOT alter public.generated_outputs,
-- public.native_social_post_artifacts or any 1.0 policy/data.
begin;

create table if not exists public.native_offer_artifacts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_id uuid not null,
  request jsonb not null check (jsonb_typeof(request) = 'object'),
  artifact jsonb not null check (jsonb_typeof(artifact) = 'object'),
  generation jsonb not null check (jsonb_typeof(generation) = 'object'),
  rendered_text text not null check (octet_length(rendered_text) <= 50000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint native_offer_user_request_unique unique (user_id, request_id)
);

alter table public.native_offer_artifacts enable row level security;
alter table public.native_offer_artifacts force row level security;

-- Idempotent policy install, scoped only to the new Slice 2 table.
drop policy if exists "native offers owner select" on public.native_offer_artifacts;

revoke all on table public.native_offer_artifacts from anon;
revoke all on table public.native_offer_artifacts from authenticated;
grant select on table public.native_offer_artifacts to authenticated;

create policy "native offers owner select"
on public.native_offer_artifacts
for select
to authenticated
using ((select auth.uid()) = user_id);

-- Mutations are route-only through service role after verified auth, entitlement,
-- UUID allowlist, origin check, validation, quota, and explicit owner predicates.
create index if not exists native_offer_user_created_idx
  on public.native_offer_artifacts (user_id, created_at desc);

commit;
