-- CE-1 local candidate: additive isolated artifact table only.
-- PREPARED ONLY. Do not apply without separate production authorization.
begin;

create table if not exists public.native_content_engine_artifacts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_id uuid not null,
  request jsonb not null check (jsonb_typeof(request) = 'object'),
  artifact jsonb not null check (jsonb_typeof(artifact) = 'object'),
  generation jsonb not null check (jsonb_typeof(generation) = 'object'),
  source_social_post_id bigint null,
  source_social_post_status text null check (source_social_post_status in ('draft', 'approved') or source_social_post_status is null),
  source_text_hash text not null check (source_text_hash ~ '^[0-9a-f]{64}$'),
  before_text text not null check (octet_length(before_text) <= 20000),
  improved_text text not null check (octet_length(improved_text) <= 25000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint native_content_engine_user_request_unique unique (user_id, request_id)
);

alter table public.native_content_engine_artifacts enable row level security;
alter table public.native_content_engine_artifacts force row level security;

drop policy if exists "native content engine owner select" on public.native_content_engine_artifacts;

revoke all on table public.native_content_engine_artifacts from anon;
revoke all on table public.native_content_engine_artifacts from authenticated;
grant select on table public.native_content_engine_artifacts to authenticated;

create policy "native content engine owner select"
on public.native_content_engine_artifacts
for select
to authenticated
using ((select auth.uid()) = user_id);

create index if not exists native_content_engine_user_created_idx
  on public.native_content_engine_artifacts (user_id, created_at desc);

commit;
